### ISSUE TITLE
Link roto

### ISSUE THREAD

**Issue by vicboma1** [korlibs/korge#10]
El link (All Soywiz's KORLIBS) que apunta a : https://github.com/soywiz/korlibs está roto

**Comment by soywiz** [comment]
Ey Victor!, thanks for noticing :) 

In the end I merged all the libraries into a single mono-repo to allow to make changes faster.
I have some local changes with simplifications, cleanups and preparing the code for a later migration to kotlinx.coroutines, but the effort is paused.

I planned to finish it this weekend since I left it almost ready the last time; but me and my wife got a pretty bad cold this week, and we are pretty sick and recovering more slowly than I would like, and I will have to catch up my work first once recovered.

Other think I want to do later is to try to target korlibs and https://github.com/kpspemu/kpspemu to kotlin-native now that it is more mature and support gradle artifacts. But this will have to wait too for now.
And use something like https://github.com/asmjit/asmjit for https://github.com/korlibs/dynarek
Lots of interesting stuff, but bit by bit.

BTW do you want a challenge?
Make a https://es.wikipedia.org/wiki/Brainfuck interpreter that can run the brainfuck samples from the wikipedia,
and then make it super fast with https://github.com/korlibs/dynarek :)

**Comment by vicboma1** [comment]
My gameboy emulator after refactoring it with kotlin has improved, but I still have some incorrect interruptions ... : C

I think that applying brainfuck to the emulator will make it faster, but the problem is not to the velocity but another. 

I see the challenge Carlos, I hope to have a little time this weekend. dynarek has good pint, it is a magic lib 
-yatuzabepapito-    <[^_^ ]>!
