### ISSUE TITLE
ConcurrentModificationException in Graphics.renderInternal

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#15]
I don't know how to reproduce it, but this happen "sometimes" when I run my current [HitKlackOnKorGE ](https://github.com/TobseF/HitKlackOnKorGE) project. 

**Start**: runJVM, **System**: Win 10 x64

> Have you tried turning it off and on again?

Yes, and it solves the problem without any changes on the code! So maybe it's the time the window gets the focus. 

**Full Stacktrace:**
```java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at com.soywiz.korge.view.Graphics.renderInternal(Graphics.kt:248)
	at com.soywiz.korge.view.View.render(View.kt:431)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:90)
	at com.soywiz.korge.view.Stage.renderInternal(Views.kt:287)
	at com.soywiz.korge.view.View.render(View.kt:431)
	at com.soywiz.korge.view.Views.render(Views.kt:175)
	at com.soywiz.korge.view.Views.frameUpdateAndRender-_rozLdE(Views.kt:204)
	at com.soywiz.korge.Korge$prepareViews$17.invoke(Korge.kt:355)
	at com.soywiz.korge.Korge$prepareViews$17.invoke(Korge.kt:31)
	at com.soywiz.korev.EventDispatcher$Mixin.dispatch(EventDispatcher.kt:46)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$2.invoke(DefaultGameWindowJvm.kt:388)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$2.invoke(DefaultGameWindowJvm.kt:18)
	at com.soywiz.korio.async.Signal.invoke(Signal.kt:110)
	at com.soywiz.korag.AGAwt$glEventListener$1.display(GLExt.kt:121)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1424)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1438)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:505)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:559)
	at com.jogamp.opengl.awt.GLCanvas.update(GLCanvas.java:866)
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
	at sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.awt.Component.dispatchEventImpl(Component.java:4965)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)```

**Comment by soywiz** [comment]
Sorry for the delay. I'm aware of this issue. It is hopefully fixed in master (this reduces allocations, but also allows to add components or other stuff on the children while iterating it):
https://github.com/korlibs/korge/commit/670e32159a0295fb51346d92dc1f15e17c04b846

I will release it as a patch version this weekend, so let's keep this open, and let me know if the issue persists after it.

**Comment by TobseF** [comment]
The `ConcurrentModificationException` still happens on korge 1.1.3.
It happens in here: `Graphics.renderInternal(ctx: RenderContext)` in the unchanged:
``` kotlin
val bounds = shapes.map { it.getBounds() }.bounds()
```

**Comment by soywiz** [comment]
Can you try?

```
git clone https://github.com/korlibs/korge.git
cd korge
./gradlew :korge:publishJvmPublicationToMavenLocal :korge:publishJsPublicationToMavenLocal :korge:publishMetadataPublicationToMavenLocal
```

**Comment by TobseF** [comment]
I tried... and after a small fight against gradle caches... yes it works seamless without any exception. So again, thank you for this great support and the super fast fixing👍
