### ISSUE TITLE
In 4.0.0-beta2, The Scene seems impossible to resume

### ISSUE THREAD

**Issue by kirk88** [korlibs/korge#1514]
On Android devices, when the activity is resumed, the screen turns black, everything that was drawn is gone.
I only found this issue in the latest version, the old version is normal.

**Comment by soywiz** [comment]
Might be releated con context lost. I belived that I fixed it, but I guess we should find a way to automatically simulate it and test it, since this is usually a regression

**Comment by kirk88** [comment]
After updating to 4.0.0beta3, the problem persisted, I made new discoveries, and sometimes after a dozen seconds, the scene actually resumed.

https://user-images.githubusercontent.com/72687899/230539319-cb0a9959-cd50-41cb-b7a7-20cd69545ad8.mp4


https://user-images.githubusercontent.com/72687899/230539396-ef38ed66-74dd-4dbc-81df-460070c47522.mp4

**Comment by kirk88** [comment]
I tried to look for problems from source code, but as a beginner it was a bit difficult for me，currently working well with GLSurfaceView.setPreserveEGLContextOnPause.

**Comment by soywiz** [comment]
Thanks for the insights! Im in a small break. I will investigate in a few days in detail. I will use that workaround if required.

Also I would like to figure out the root cause since that might affect other targets where a context lost is less likely to happen but might happen too.
Im considering doing in a JVM test a forced context lost by actually creating a new context and replacing the AG instance with it to simulate GL objects to not be available and ensure they are recreated as required (including vertices, buffers, textures and shaders) and a render happens normally after that. Hopefully that will avoid further regressions in all the targets.

**Comment by kirk88** [comment]
Thanks, hoping for a better solution as I'm trying to use Korge in my project.
